export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENT='SET_INGREDIENT';
export const FECTCH_INGREDIENT_FAILED='FECTCH_INGREDIENT_FAILED';

export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUSCESS='PURCHASE_BURGER_SUSCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';
export const PURCHASR_INIT='PURCHASR_INIT';

export const ORDER_START='ORDER_START';
export const ORDER_SUCCESS='ORDER_SUCCESS';
export const ORDER_FAIL='ORDER_FAIL';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';